Traceback (most recent call last):
  File "/home/mfvargas/miniconda3/envs/pf3311-2025-ii/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mfvargas/miniconda3/envs/pf3311-2025-ii/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/home/mfvargas/miniconda3/envs/pf3311-2025-ii/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/mfvargas/miniconda3/envs/pf3311-2025-ii/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/mfvargas/miniconda3/envs/pf3311-2025-ii/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/mfvargas/miniconda3/envs/pf3311-2025-ii/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/home/mfvargas/miniconda3/envs/pf3311-2025-ii/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mfvargas/miniconda3/envs/pf3311-2025-ii/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Mapa de Stamen Terrain
m = folium.Map(
    location=[10, -84], 
    width=650, height=400, 
    zoom_start=5, 
    tiles='Stamen Terrain')
m
------------------


[31m---------------------------------------------------------------------------[39m
[31mValueError[39m                                Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[5][39m[32m, line 2[39m
[32m      1[39m [38;5;66;03m# Mapa de Stamen Terrain[39;00m
[32m----> [39m[32m2[39m m = [43mfolium[49m[43m.[49m[43mMap[49m[43m([49m
[32m      3[39m [43m    [49m[43mlocation[49m[43m=[49m[43m[[49m[32;43m10[39;49m[43m,[49m[43m [49m[43m-[49m[32;43m84[39;49m[43m][49m[43m,[49m[43m [49m
[32m      4[39m [43m    [49m[43mwidth[49m[43m=[49m[32;43m650[39;49m[43m,[49m[43m [49m[43mheight[49m[43m=[49m[32;43m400[39;49m[43m,[49m[43m [49m
[32m      5[39m [43m    [49m[43mzoom_start[49m[43m=[49m[32;43m5[39;49m[43m,[49m[43m [49m
[32m      6[39m [43m    [49m[43mtiles[49m[43m=[49m[33;43m'[39;49m[33;43mStamen Terrain[39;49m[33;43m'[39;49m[43m)[49m
[32m      7[39m m

[36mFile [39m[32m~/miniconda3/envs/pf3311-2025-ii/lib/python3.13/site-packages/folium/folium.py:345[39m, in [36mMap.__init__[39m[34m(self, location, width, height, left, top, position, tiles, attr, min_zoom, max_zoom, zoom_start, min_lat, max_lat, min_lon, max_lon, max_bounds, crs, control_scale, prefer_canvas, no_touch, disable_3d, png_enabled, zoom_control, font_size, **kwargs)[39m
[32m    343[39m     [38;5;28mself[39m.add_child(tiles)
[32m    344[39m [38;5;28;01melif[39;00m tiles:
[32m--> [39m[32m345[39m     tile_layer = [43mTileLayer[49m[43m([49m
[32m    346[39m [43m        [49m[43mtiles[49m[43m=[49m[43mtiles[49m[43m,[49m[43m [49m[43mattr[49m[43m=[49m[43mattr[49m[43m,[49m[43m [49m[43mmin_zoom[49m[43m=[49m[43mmin_zoom[49m[43m,[49m[43m [49m[43mmax_zoom[49m[43m=[49m[43mmax_zoom[49m
[32m    347[39m [43m    [49m[43m)[49m
[32m    348[39m     [38;5;28mself[39m.add_child(tile_layer, name=tile_layer.tile_name)

[36mFile [39m[32m~/miniconda3/envs/pf3311-2025-ii/lib/python3.13/site-packages/folium/raster_layers.py:142[39m, in [36mTileLayer.__init__[39m[34m(self, tiles, min_zoom, max_zoom, max_native_zoom, attr, detect_retina, name, overlay, control, show, no_wrap, subdomains, tms, opacity, **kwargs)[39m
[32m    140[39m [38;5;28mself[39m.tiles = tiles
[32m    141[39m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m attr:
[32m--> [39m[32m142[39m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([33m"[39m[33mCustom tiles must have an attribution.[39m[33m"[39m)
[32m    144[39m [38;5;28mself[39m.options = remove_empty(
[32m    145[39m     min_zoom=min_zoom [38;5;129;01mor[39;00m [32m0[39m,
[32m    146[39m     max_zoom=max_zoom [38;5;129;01mor[39;00m [32m18[39m,
[32m   (...)[39m[32m    154[39m     **kwargs,
[32m    155[39m )

[31mValueError[39m: Custom tiles must have an attribution.

